[workspace]
default-members = ["shipcat_cli"]
members = [
  "raftcat",
  "shipcat_cli",
  "merge",
  "merge_derive",
  "shipcat_filebacked",
]
# Definitions has its own workspace atm.
exclude = ["shipcat_definitions"]

[profile.release]
debug = false
