[package]
authors = ["Eirik Albrigtsen <eirik.albrigtsen@babylonhealth.com>"]
name = "shipcat"
readme = "README.md"
version = "0.2.0"

[[bin]]
doc = false
name = "shipcat"
path = "src/main.rs"

[dependencies]
clap = "2.29.1"
error-chain = "0.11.0"
hyper = "0.11.14"
log = "0.4.1"
loggerv = "0.7.0"
openssl-probe = "0.1.2"
reqwest = "0.8.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_yaml = "0.7.3"
slack-hook = "0.6.0"
tera = "0.10.10"
walkdir = "2.0.1"

[lib]
name = "shipcat"
path = "src/lib.rs"
