version: 2
workflows:
  version: 2
  compile_build_and_release:
    jobs:
      - compile_app
      - build_image
jobs:
  compile_app:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/shipcat
          destination: shipcat
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
  build_image:
    machine: true
    steps:
      - checkout
      - run: ls **
      - login: |
         docker --version
         docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io

      # build the kubcat image using the compiled binary and push it
      - run: make tag-latest
