version: 2
workflows:
  version: 2
  compile_build_and_release:
    jobs:
      - compile_app
      # TODO: github releases rather than circi build artifacts
      # TODO: osx artifacts
jobs:
  compile_app:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/shipcat
          destination: shipcat
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
