version: 2
workflows:
  version: 2
  comiple_and_build:
    jobs:
      - compile_app
      - build_image:
          requires:
            - compile_app
jobs:
  compile_app:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/shipcat
          destination: shipcat
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - shipcat
  build_image:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls -lah *
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
      - run: make tag-release
