version: 2
workflows:
  version: 2
  shipcat_flow:
    jobs:
      - musl_build
      - cargo_test:
          filters:
            branches:
              ignore:
                - master
      - docker_build:
          requires:
            - musl_build
          filters:
            branches:
              only:
                - master
jobs:
  musl_build:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry-{{ checksum "Cargo.lock" }}
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/shipcat
          destination: shipcat
      - save_cache:
          key: cargo.registry-{{ checksum "Cargo.lock" }}
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - shipcat

  cargo_test:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    environment:
      - RUST_BACKTRACE: "full"
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry-{{ checksum "Cargo.lock" }}
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo test -- --nocapture
      - run: cargo doc --no-deps

  docker_build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
      - run: ls -lah **
      - run: make build
      - run: make install
      - run: make tag-latest
      - run: make tag-semver
