[package]
name = "raftcat"
version = "0.1.0"
authors = ["Eirik Albrigtsen <eirik.albrigtsen@babylonhealth.com>"]

[dependencies]
shipcat_definitions = { path = "../shipcat_definitions", features = [] }
#k8s-openapi = { git = "https://github.com/Arnavion/k8s-openapi-codegen", branch = "master", features = ["v1_10"] }
#kubernetes = { path = "../../kubernetes-rust" }
kubernetes = { git = "https://github.com/ynqa/kubernetes-rust", rev = "9c5f29f1f70d31042371db8ed6782486a41c8e3b" }
serde_json = "1.0.32"
serde = "1.0.80"
serde_derive = "1.0.80"
url = "1.7.2"
http = "0.1.13"
failure = "0.1.3"
actix-web = "0.7.13"
env_logger = "0.5.13"
actix = "0.7.6"
