[package]
name = "raftcat"
version = "0.1.0"
authors = ["Eirik Albrigtsen <eirik.albrigtsen@babylonhealth.com>"]

[dependencies]
shipcat_definitions = { path = "../shipcat_definitions", features = [] }
kubernetes = { git = "https://github.com/clux/kubernetes-rust", rev = "8f31e6c80ebf204d1f26ffa8b20d855357f118d7" }
#kubernetes = { path = "../../kubernetes-rust" }
serde_json = "1.0.32"
serde = "1.0.80"
serde_derive = "1.0.80"
url = "1.7.2"
http = "0.1.13"
failure = "0.1.3"
actix-web = "0.7.13"
env_logger = "0.5.13"
actix = "0.7.6"
log = "0.4.6"
