[package]
name = "raftcat"
version = "0.1.0"
authors = ["Eirik Albrigtsen <eirik.albrigtsen@babylonhealth.com>"]

[dependencies]
shipcat_definitions = { path = "../shipcat_definitions", features = [] }
kubernetes = { git = "https://github.com/clux/kubernetes-rust", rev = "e2c118e88fe20342599756b23156c5121d03a63a" }
serde_json = "1.0.32"
serde = "1.0.80"
serde_derive = "1.0.80"
url = "1.7.2"
http = "0.1.13"
failure = "0.1.3"
actix-web = "0.7.13"
env_logger = "0.5.13"
actix = "0.7.6"
